iraf-community/iraf

- unix/f2c/src/init.c
To change the size of `INTEGER` to 64 bit it is __not enough__ to just patch `f2c.h`, also the length of an integer must be adjusted in the f2c sources, since it is f.e. needed to determine the largest type to use in an `EQUIVALENCE` statement. Otherwise, the wrong type may be used there as the general type. This happens f.e. in [`ieeer.x`](https://github.com/iraf/iraf-v216/blob/9590f45760a4791f3305407fb51c87f1282b32be/sys/osb/ieeer.x#L101-L105):
```
int	expon, i, val
real	fval
int	ival[1]
%	equivalence (fval, ival)
%	equivalence (ival, val)
```
translates by the current `f2c.e` to
```
static real equiv_1[1];
/* Local variables */
static integer i__;
#define val ((integer *)equiv_1)
#define fval (equiv_1)
#define ival ((integer *)equiv_1)
```
This is wrong: on ILP64, `real` is a 4-byte …
> Adjust Integer size for ILP64

- unix/hlib/login.cl
Since the official IRAF (iraf.noao.edu) is not going to be updated anymore, there is no reason to check for updates then. To protect users privacy, and to avoid startup delays, this PR will disable the check.
> Don't check for updates

- pkg/softools/mkapropos.hlp
- pkg/softools/mkapropos.par
- pkg/softools/mkapropos/help.h
- pkg/softools/mkapropos/helpdir.h
- pkg/softools/mkapropos/helpdir.x
- pkg/softools/mkapropos/mkpkg
- pkg/softools/mkapropos/strext.x
- pkg/softools/mkapropos/t_mkapropos.x
- pkg/softools/mkapropos/word.x
- pkg/softools/mkpkg
- pkg/softools/softools.cl
- pkg/softools/softools.hd
- pkg/softools/softools.men
- pkg/softools/x_softools.x
- pkg/system/apropos.cl
- pkg/system/system.cl
- unix/hlib/extern.pkg
`apropos` searches the documentation for a given keyword. This patch also includes the tasks required to build the apropos database.
This is taken from the STSCI Ureka svn tree, mostly from adbb8e6589867f63b4844b05fd8d3faa2ea35aff committed by @jehturner.
> Implement the 'apropos' command

- vendor/libvotable/votHandle.c
The loop variable is [counted down as long as it is not negative](https://github.com/iraf-community/iraf/blob/667d7eba16e599d3fc75492e8648d36c950388db/vendor/libvotable/votHandle.c#L113). This however requires the variable to be a signed `int`.
> votable: Fix data type of loop variable

- noao/obsutil/src/findgain.cl
Closes #46 - Thanks to @dxwayne for the fix!
Quoting:
> Cause: The variables are declared with one spelling, the code attempts to work with a slightly different spelling. This is one fix: may choose to alter the few more lines to use the original spelling.
> 
> test:
> ```
> findgain flat1.fits flat2.fits zero1.fits zero2.fits section="[650:750,650:750]"
> ```
> where the fits files are zeros/flats at least this big.
>
> Fix variable declaration in noao/obsutil/src/findgain.cl

- unix/hlib/cl.sh
- unix/hlib/ecl.sh
With the removal of vocl (iraf/iraf-v216#93), this can't be used as the default shell anymore; so we set the default shell to ecl.e.
> Set ecl as the default shell

- install
Csh scripts  (specifically `unix/hlib/setup.csh`) were removed in 8a4738871e421dea31981f4eff606eeebd0dcef4
> Remove patching of non-existing setup.csh

- sys/tty/ttygsize.x
- sys/tty/ttyodes.x
- unix/hlib/libc/knames.h
- unix/os/mkpkg
- unix/os/zttyio.c
This is a nice [cherry-pick](https://sourceforge.net/p/iraf64/code/276/) from the [iraf64](https://www.ir.isas.jaxa.jp/~cyamauch/iraf64/index.html) project by @cyamauch .
This makes terminal resizing working again, and so fixes the issue iraf/iraf-v216#118.
```
$ echo $TERM
xterm
$ resize
COLUMNS=80;
LINES=24;
export COLUMNS LINES;
$ cl
[...]
ecl> stty 
xterm ncols=80 nlines=24 
```
Without this PR, it shows the wrong `nlines=65` here.  Nice side effect is that one does not get a timeout anymore when the wrong terminal was set.
See also [iraf.net](http://iraf.net/forum/viewtopic.php?showtopic=1467258). I am wondering why this did not make the way into the NOAO code base 10 years ago?
> Appended `ZTTYSZ()` function to get width and height of terminal

- .travis.yml
Only for the 64-bit version.
In the 32-bit version, the compilation output is messed up with deprecation warnings, therefore some tests (which require compilation) fail. So we stay with 9.4 there.
> Update Xcode version to 10.0 in Travis tests

- unix/boot/bootlib/bytmov.c
- unix/boot/bootlib/oschdir.c
- unix/boot/bootlib/osgetenv.c
* add missing return type to `BYTMOV`
* declare memmove via `#include <string.h>`
* declare `ZGTENV()` in `os_getenv.c`
> Improve prototyping in bootlib

- pkg/cl/exec.c
- pkg/ecl/exec.c
From [iraf.net](http://iraf.net/forum/viewtopic.php?showtopic=1469897) (user mcba):
> Hi guys,
> 
> I'm trying to use an IRAF command in a bash script, so I am creating a file like this:
>```
>#!/home/mcba/miniconda3/envs/iraf27/iraf/bin.linux/ecl.e -f
>task $hello=/home/mcba/iraf/hello.e
>imhead g.fits
>hello
>logout
>```
> When I run this, the "imhead" command works fine, but the "hello" command results in:
>```
>ERROR: segmentation violation
>called as: `cl ()'
>Error while reading login.cl file - may need to rebuild with mkiraf
>Fatal startup error. CL dies.
>```
> Interestingly, the cl doesn't get as far as even looking at `hello.e`. I can replace the above task line with
>```
>task $hello=dummy
>```
> and I get exactly the same error message. But if I use `$dummy`, then hello gets …
> Check for the existence of the "arch" variable before using it

- pkg/utilities/mkpkg
Otherwise, the `x_nttools.e` task is built twice, but the second built is not moved and kept in `pkg/utilities/nttools/`. This will unnecessarily increase the size of the binary packages.
> Adjust calling of nttools subdir in pkg/utilities/mkpkg

- unix/boot/bootlib/mkpkg.sh
- unix/boot/generic/mkpkg.sh
- unix/boot/mkpkg.sh
- unix/boot/mkpkg/mkpkg.sh
- unix/boot/rmbin/mkpkg.sh
- unix/boot/rmfiles/mkpkg.sh
- unix/boot/rtar/mkpkg.sh
- unix/boot/spp/mkpkg.sh
- unix/boot/spp/rpp/mkpkg.sh
- unix/boot/spp/rpp/ratlibc/mkpkg.sh
- unix/boot/spp/rpp/ratlibf/mkpkg.sh
- unix/boot/spp/rpp/rppfor/mkpkg.sh
- unix/boot/spp/xpp/mkpkg.sh
- unix/boot/wtar/mkpkg.sh
- unix/boot/xyacc/mkpkg.sh
- unix/f2c/libf2c/mkpkg.sh
- unix/f2c/mkpkg.sh
- unix/f2c/src/mkpkg.sh
- unix/gdev/mkpkg.sh
- unix/gdev/sgidev/mkpkg.sh
- unix/mkpkg.sh
- unix/os/mkpkg.sh
- util/mksysgen
- vendor/cfitsio/mklibs
- vendor/mklibs
- vendor/trim_cfitsio.sh
This requires the removal ot the build log redirection in `util/mksysgen`. 
Also, the shebang is added to the `mkpkg.sh` scripts.
I am not very sure about this: it may be better to just replace all the `mkpkg.sh` scripts by proper Makefiles (they are simple anyway), and to merge `util/mksysgen` into the toplevel Makefile. This would bring the IRAF build system closer to the standard, and also has the effect to properly fail on build errors. @iraf, any opinion on this?
> Fail on error when running build scripts

- unix/as.linux64/zsvjmp.S
- unix/as.macintel/zsvjmp.s
The iraf64 web page [states]( https://www.ir.isas.jaxa.jp/~cyamauch/iraf64/index.html) for their own code (which is there at least since **Jan 2008**)
> Updates for x86_64
>     Wrote an assembler code for Linux x86_64 architecture.
https://github.com/iraf-community/iraf/blob/6687c734978c66909648cdb4b899942da147d65f/iraf/unix/as.x86_64-linux-generic/zsvjmp.s#L38-L44
The code here is identical, except for white spaces, and appeared only **Nov 2010**:
https://github.com/iraf-community/iraf/blob/b499169fe25dee4410cac1c27b239562df98f0ce/unix/as.linux64/zsvjmp.s#L41-L47
So, I am quite sure that the IRAF code for amd64 zsvjmp was "taken over" from the iraf64 project, and therefore should get the proper copyright assignment. Interestingly, this file is not mentioned in the `notes.v214` or …
> Mention Chisato Yamauchi as copyright owner of the x86_64 zsvjmp.s code

- pkg/system/chkupdate.x
- pkg/system/t_urlget.x
- sys/etc/urlget.x
- sys/etc/zzdebug.x
- sys/imio/imt/t_urlget.x
Sometimes, the HTTP response header is larger than `SZ_PATHNAME` (512 chars). This may happen especially when the URL redirects to a content delivery service. In this case, the end of the redirected URL was cut (resulting in a failing download), or the program even segfaulted.
This patch increases the size of the reply buffer to `SZ_BUF` (8192 chars), and also takes care that the program does not crash when the header is larger. The response URL however is still limited to `SZ_LINE` (1023 chars).
Note that these limits are still arbitrary and may be too short: the maximum *recommended* size for an URL is 2048, and the HTTP response header has no size limit at all. `SZ_LINE` is however builtin in many places of string processing, so it is probably not easy to increase the max URL size to …
> Fix buffer length in urlget.x

- unix/as.linux64/zsvjmp.S
[RISC-V](https://riscv.org/) (pronounced "risk-five") is an open instruction set architecture (ISA) based on established reduced instruction set computing (RISC) principles. While there are still no real hardware CPUs available, there is already Linux support with it, and it exists an (unofficial) [Debian port](https://wiki.debian.org/RISC-V).
This patch provides the assembler code in `zsvjmp.S` to support riscv64. It is based on
https://lists.debian.org/debian-riscv/2018/10/msg00012.html
and the code was written and tested by Manuel A. Fernandez Montecelo and Stefan O'Rear.
> Add riscv64 support

- INSTALL.md
So, users can check whether their CPU is supported before build. This needs to be kept up-to-date, however.
> Add supported CPUs to install document

- unix/hlib/cl.sh
- unix/hlib/ecl.sh
- unix/hlib/mkiraf.sh
irafarch is now a `/bin/sh` script, and has the suffix `.sh`. This was forgotten to change in #54, and also another small glitch was introduced there.
Should have tested it more carefully... :-(
> Fix usage irafarch.sh in (e)cl.sh

- .travis.yml
The old archs are outdated and subject of removal from Travis. And we had no problems ever for them when built from source. We should concentrate here on newer systems. This will speed up the tests by a factor of 2.
Occasional tests will run locally however on older systems is an incompatibility is suspected (remembering that @iraf still has a RHEL-7 system).
We could think of dropping OS-X 32 bit tests, as 32 bit is going less and less supported by the OS.
> Remove old architectures from Travis tests

- INSTALL.md
- unix/as.linux64/zsvjmp.S
One of the platforms Debian is ported to is the DEC Alpha processor. Since there already was a port to that CPU in the nineties, we can just re-use the assembler code from that time.
This is just uploaded to Debian, check [here](https://buildd.debian.org/status/logs.php?pkg=iraf&arch=alpha) for the build (and test) log. Once it succeeds there, this could be merged into the upstream sources.
> (Re-) add the alpha version of zsvjmp.s

- .travis.yml
This PR updates the tests to the latest OS versions available on travis:
* MacOS Mojave 10.14 (64 bit); xcode 10.2
* Ubuntu 16.04 Xenial (32 and 64 bit)
The 32-bit version remains on xcode 9.4 (macOS 10.13 High Sierra)
> Update OS versions for tests

- .travis.yml
- install
The system installation is somehow flaky: It tries to create a symlink as `/iraf`. This link contradicts any file system standards and is buggy by design: It silently requires that the IRAF directory is called `iraf`
by itself, which is not always the case. This symlink is also not necessary at all, since the proper install path is determined with the link of `/usr/include/iraf.h` or the `iraf` environment variable.
So, we remove the creation of this link.
Also, it tries to create links for x11iraf, which is not part of the iraf-community distribution. We also remove creation of this link.
And finally, the possibility to change the "new iraf root" is misleading (it **must** be the directory where the `install` script is in), and is therefore removed.
This closes #83.
It supercedes #84 …
> Fix system install

- unix/hlib/irafuser.csh
Tcsh aborts sourcing the script if it tries to access an undefined variable. This change makes it sure that the variables (except $iraf) are defined before accessing them.
Also, we make sure that no double slashes are in the defined variables.
> Fix irafuser.csh

- doc/LICENSES/LAPACK
- doc/LICENSES/README
This license is used for `math$lapack`.
Taken from https://github.com/Reference-LAPACK/lapack/blob/12d825396fcef1e0a1b27be9f119f9e554621e55/LICENSE
> Add LAPACK license

- INSTALL.md
I propose a small addition to the instructions in INSTALL.md It may be helpful to inform the user that the IRAF bin directory specified by the user to the install script should be added to PATH variable. If it is not done, the following `make` step fails not finding the `xc` command. The solution to this problem is kind of obvious, but still mentioning it in the installation instructions will save some minutes and nerve cells for the new users.
> add note about the path to iraf bin dir to INSTALL.md

- .travis.yml
The PR updates the Travis build environments to Ubuntu 18.04 "Bionic" and macOS 10.15 "Catalina" (XCode 11.2, 64 bit). The macOS 32-bit environment stays at 10.13 "High Sierra" (XCode 9.4), since this is the last version that works well.
Additionally, the 64-bit ARM architecture is built (also Ubuntu 18.04 "Bionic").
> Update travis build environments

- unix/boot/bootlib/osfcopy.c
- unix/boot/mkpkg/host.c
- unix/boot/mkpkg/scanlib.c
- unix/boot/spp/xc.c
- unix/os/prwait.c
- unix/os/zfiobf.c
- unix/os/zfioks.c
- unix/os/zfiomt.c
- unix/os/zfiond.c
- unix/os/zzstrt.c
- vendor/libvotable/votParse.c
This PR removes a few compiler warnings:
* unused static function `findexe()` from `xc.c` (the code of this function is removed)
* use of `NULL` as an integer parameter
* unused local variables
* deprecated `bcopy()` and `bzero()` functions (replaced by `memcopy()` and `memset()`)
* wrong (generic integer) data type instead of `in_addr_t` in `zfiond.c`
* call-by-value parameters of `ZZSETK()` in `zzstrt.c`
> Remove some C compiler warnings

- .travis.yml
... to keep the MacOS build test up to date with the latest code of the development tools
Unfortunately, we have to disable the ARM64 build since it takes too long on Travis.
> Push XCode version to 11.4 (64bit/Catalina)

- unix/boot/spp/xpp/xppcode.c
- unix/hlib/f77.sh
GCC 10 defaults to `-fno-common`, where it is an error when the same global variable is defined twice; see https://gcc.gnu.org/gcc-10/porting_to.html.
This PR resolves this (for xpp), and closes #110.
> Avoid multiple definition of errflag

- mkpkg
The top-level mkpkg calls uses `setenv` in the targets for setting up the different architectures. Although these targets are mainly unused (and therefore this problem went undiscovered for some time), it is better to clean this up (and replace them by `export` statements).
> Remove csh specifics from top-level mkpkg

- unix/as.linux/zsvjmp.S
With gcc-10, the linkes issues a warning when trying to call sigsetjmp directly on i386:
```
…/libos.a(zsvjmp.o): warning: relocation against `__sigsetjmp@@GLIBC_2.0' in read-only section `.text'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
```
This can be avoided to use the Procedure Linkage Table for this function. Note that other architectures still use direct calls:
* ARM 32/64 bit
* MIPS 32/64 bit
* PowerPC 64 bit
> Use PLT when calling sigsetjmp on i386

- test/README.md
- test/os.md
- test/programming.md
- unix/os/zgmtco.c
- unix/os/zgtime.c
This should return the CPU time in milliseconds. In early versions, this was calculated as floating point `cpu*1000./clkfreq` with `clkfreq` being the clock ticks per second. At some point, floating point was tried to be avoided in the kernel, and so this got an (all integer)
cpu * 1000 / clkfreq
To prevent (undiscovered) overflow for large values of `cpu` (namely when `cpu > MAX_LONG/1000)`, the order is reversed:
cpu / clkfreq * 1000
Note that this is still the same operation, just a different order.
In version 2.15, determination of `clkfreq` seemed to be complicated as noticed in https://github.com/iraf-community/iraf/blob/216ab7d6bc20411d0dad16bde61902eee74fecd4/doc/notes.v214#L1511-L1513
It was then changed to the buggy
if (cpu > MAX_LONG/1000)
*cpu_time = cpu / 10;
else
*cpu_time = …
> Fix cpu_time calculation in unix/os/zgtime.c

- .travis.yml
- unix/os/zgmtco.c
This PR updates
* the macOS build to xCode 12.2 (still on Catalina)
* the Linux build to Ubuntu 20.04 "focal"
A minor issue was found with the macOS build: `gmt_to_lst()` needs to be declared before use.
> Update travis CI to latest macOS and Ubuntu versions

- unix/os/irafpath.c
The function `irafpath()` resolves the full path for a given IRAF file. The file is searched in the following directories:
* `host$bin(arch)`: system build executables and libraries
* `host$hlib`: include files and shell scripts
* `iraf$bin(arch)`:  IRAF executables and libraries
* `iraf$lib`: IRAF include files and libraries (links)
While `iraf$bin(arch)` is created from IRAFARCH, `host$bin(arch)` is hardcoded by defines like `#ifdef __x86_64__`. This has two disadvantages: First, it fixes the architecture names in the executable, and second it requires a source change for every new arch. And it does not allow to have only arch-independent directory names, as it is used f.e. in Debian.
This patch unifies the handling architectures in `irafpath()`. This continues the path started with …
> Replace hard-coded host$bin paths by IRAFPATH

- test/os.md
- unix/os/zgmtco.c
Revert part of #118, where we assumed that gmtco converts GMT (Unix) time into LST. In fact this is not the case (so, I think the name is a bit misleading, as it assumes the same as `gmt_to_lst`), but it just gives the current local correction in time.
`zgmtco` gives the time difference for the following numbers:
* Seconds since 1980-01-01 local time ("LST")
* Seconds since 1980-01-01 UTC ("GMT")
Both are (should be) monotone, so the difference is just the start. Therefore, we calculate the difference on the base of the begin of the epoch, and revert (almost) to the original version from IRAF 2.11. Adding the current (!) summer time (as done in version 2.12) seems to  be a wrong idea here.
This fixes #135
> Fix fits times

- math/slalib/eqeqx.f
This is taken from a mail from Patrick Wallace <patrick.wallace@STFC.AC.UK> to the starlink-users mailing list:
> To whom it may concern...
> 
> I have discovered a decades-old bug in the SLALIB routine `sla_EQEQX`:
> 
> https://github.com/Starlink/starlink/blob/master/libraries/sla/eqeqx.f
> 
> It causes observed places (the direction of the incoming radiation from a celestial source) to be wrong by an amount that was zero at J2000.0 but grows steadily and at the present time has reached almost 0.1 arcseconds.
> 
> Corrected code (including the test program) is attached.  For anyone interested, the story is as follows.
> 
> * Using the classical pre IAU 2000 equinox based methods, hour angles are obtained by subtracting apparent right ascension from the local apparent sidereal time.
> 
> …
> SLALIB bug

- INSTALL.md
- Makefile
- mkpkg
- noao/mkpkg
- pkg/cl/exec.c
- pkg/ecl/exec.c
- pkg/ecl/grammar.y
- pkg/ecl/mkpkg
- pkg/ecl/ytab.c
- test/run_tests
- unix/hlib/cl.sh
- unix/hlib/ecl.sh
- unix/hlib/irafarch.sh
- unix/hlib/strip.iraf
- unix/os/zsvjmp.S
This needs some changes:
- **`macos64`**, which would be the logical analogon to `linux64`. We also could rename `macintel` at some point.
- `macarm`, which would be the logical analogon to `macintel`.
I now committed a change to `macos64`, because it is much clearer.
> Add macOS arm64 support

- install
A common mistake to run `./install` is to already have the `iraf` environment variable set. To avoid this, we check whether we are in a iraf source dir and then use iraf unconditionally.
This resolves problems as described in https://github.com/iraf-community/iraf/discussions/147
> Don't re-use existing iraf env var

- unix/boot/spp/rpp/mkpkg.sh
The `RATFOR` variable is used to determine whether we want Ratfor preprocessing (see #103); however it was references by `$(RATFOR)` instead of `${RATFOR}` in the shell script. This patch fixes this (used in the Debian build, as Debian builds completely from sources).
> Fix test for RATFOR variable

- unix/hlib/irafarch.sh
This patch makes the test for freebsd more generic, as there exist some exotic variants: kfreeBSD is a Debian on top of a freeBSD kernel. The architecture string then is "gnu/kfreebsd".
So, we enable wildcard prefixes to `freebsd` to check it..
> Support freeBSD variants

- unix/hlib/extpkg.cl
- unix/os/zoscmd.c
Some shells behave differently; namely zsh prints a warning itself when a glob doesn't match.  This is f.e. the case when one tries to get the list of external packages from an empty dir with https://github.com/iraf-community/iraf/blob/bcb80b314cbd8c4ee253abec1e2ca64645428579/unix/hlib/extpkg.cl#L26
With zsh, this leads to a message "no matches found" which disturbs f.e. the tests. See f.e. https://github.com/iraf-community/iraf/discussions/178#discussioncomment-882244 for such a failure.
The solution is to use `!!`  in the cl script so that `/bin/sh` is forced to be used. Generally, the scripts provided by IRAF should be independent of the user's shell (just checked that this is the only place where this happens).
> Force using POSIX shell in extpkg.cl script

- noao/imred/src/fibers/fibresponse.cl
Duplicate arguments are not needed, and they confuse PyRAF (as discovered when test-compiling all IRAF CL procedures with PyRAF)
The other problem is the `default` argument in https://github.com/iraf-community/iraf/blob/6ba125dfa9da44704e345b695b159985720ce2b0/noao/imred/crutil/src/credit.cl#L6-L12
which converts to illegal Python code. This is unresolved now.
> Remove duplicate argument in call

- CREDITS.md
The basic idea is to keep the names of those who contributed to IRAF.
> [skip ci] Add IRAF authors list

- unix/gdev/sgidev/sgi2uhplj.c
There are two places where space for the trailing '\0' of a string was not properly allocated.
> Fix off-by-one allocation error in sgi2uhplj.c

- unix/hlib/util.sh
This string is displayed when invoking `./install`.
> Update remaining version string

- Makefile
- install
- pkg/cl/cl.par
- pkg/ecl/cl.par
These have been forgotten in #170 (616fe81332e3ca4eeb734ddfc805f11b6d332bd9) before the release.
Closes: #220
> Update remaining version numbers to 2.17

- .github/workflows/citest.yml
This is the latest version (currently in Beta for Github Actions).
> Switch macOS test build environment to macOS 12 (Monterey)

- unix/os/zsvjmp.S
Modern gcc on ELF systems require an explicit mark of whether the stack is executable or not. This one marks the stack as *not* executable.
> Add .note.GNU-stack section to zsvjmp.S

- unix/os/zfiopr.c
- unix/os/zopdpr.c
- unix/os/zoscmd.c
`vfork()` is marked obsolete in POSIX.1-2001 and was removed from Posix in POSIX.1-2008. Newer macOS compilers warn about this, so we remove it. `vfork()` was used in Debian only for speed improvements by avoiding copying the address space; however modern systems use copy-on-write, this argument is not actual anymore.
> Replace vfork() with fork()

- unix/hlib/mkfloat
This is required to use mkfloat (when building an external package) with the "-d" option.
> Fix a bug in the parsing of directory arguments of mkfloat

- unix/boot/mkpkg/extern.h
- unix/boot/mkpkg/host.c
- unix/boot/mkpkg/main.c
- unix/boot/mkpkg/mkpkg.h
- unix/boot/mkpkg/mkpkg.hlp
- unix/boot/mkpkg/mkpkg.man
- unix/boot/mkpkg/pkg.c
- unix/boot/mkpkg/scanlib.c
- unix/boot/mkpkg/tok.c
- unix/boot/spp/xc.c
- unix/boot/spp/xc.hlp
- unix/boot/spp/xc.man
This PR syncs the online documentation and manpages and the source code for xc and mkpkg: 
* remove documentation of options that are not available (either removed, or not available on Unix hosts)
* Remove few options from the sources that are not implemented:
- xc **-G** (force a program to link w/ libg2c.a instead of libf2c.a)
- xc **-r** (dummy; set irafdir before)
- mkpkg **-r** (set irafdir)
- mkpkg **-u** (forcibly update libmod dates)
Also, VMS specifics were removed.
> Update host commands documentation

- mkpkg
- unix/boot/mkpkg/char.c
- unix/boot/mkpkg/host.c
- unix/boot/mkpkg/main.c
- unix/boot/mkpkg/mkpkg.h
- unix/boot/mkpkg/mkpkg.hlp
- unix/boot/mkpkg/mkpkg.man
- unix/boot/mkpkg/pkg.c
- unix/boot/mkpkg/scanlib.c
- unix/boot/mkpkg/tok.c
One annoying thing of the IRAF build is that errors during the build process are almost ignored, and the build process continues. First, this makes it hard to check if the compilation finally succeeded, then it is a waste of time, and finally, it is very hard to find where the error actually appeared.
This PR solves this by letting mkpkg fail whenever an error appeared. This is implemented by an **errors()** function which complements the existing **warns()** and **fatals()**. While **warns()** just continues, and **fatals()** always exits with an error, **errors()** exits only if the **-i** flag (ignore errors) is not set.
A number of **warns()** calls are now replaced by **errors()** calls; this will make **mkpkg** more picky against errors in the control file by default, which is a …
> Stop mkpkg execution if an error was discovered

- .github/workflows/citest.yml
18.04 is deprecated since a while, and 20.04 still supports building and running 32-bit apps. So for the time being, we use this one.
> Update Ubuntu version used for 32-bit to 20.04

- unix/boot/bootlib/envinit.c
The searchs works for **set** or **reset** and is done *after* stepping over possible whitespaces. The bug here was that **set** resp. **reset** were searched in the string *before* whitespace removal, but the result was applied to the string *after* the removal. This works for
```
set foo = bar
``` 
but not for
````
set foo = bar
````
It is funny to see that this bug is there since 35 years, and nobody discovered or fixed it...
For us this is important, since otherwise the **noao** variable was not read in properly.
The second issue is that missing files produce a warning; however they may appear regularly, like in
```
if (access ("iraf$extern/.zzsetenv.def"))
set @iraf$extern/.zzsetenv.def
;
```
**envinit** does not have scripting capability; it just searches for the **set**/**reset** …
> Fix keyword search in envinit

- unix/boot/spp/xc.c
Empty arguments are sometimes wrongly intepreted by gcc (as object files) and may lead to a compilation error ("object file not found" for gcc), or possibly even to compiler crashes.
> Don't add empty arguments to xc argument lists

- unix/boot/spp/xc.c
- unix/hlib/libc/kernel.h
- unix/os/zfioks.c
- unix/os/zfiomt.c
- unix/os/zfiond.c
- unix/os/zfiotx.c
- unix/os/zwmsec.c
- unix/os/zxwhen.c
The global C type `SIGFUNC` was used of a generic signal handling function type. However, this was used for three incompatible function types:
* C signal handlers (`void  (*)(int)`), i.e. a function called with the signal number
* C signal actions (`void  (*)(int, siginfo_t *, void *)`), i.e. a function called with the signal number, additional signal information,  and some payload,
* IRAF signal handlers (`void  (*)(XINT *, XINT *)`), i.e. a function called with a pointer to the signal number and a pointer to the next handler.
Replacing these with proper types leaves only the last case in `zxwhen.c` as a use for `SIGFUNC`. However, this type is not used outside of `zxwhen.c`. As IRAF/SPP doesn't generally support function prototypes, it doesn't make sense to have it exposed anymore. …
> Replace SIGFUNC by sighandler_t

- pkg/cl/main.c
- pkg/cl/prcache.c
- pkg/ecl/main.c
- pkg/ecl/prcache.c
- sys/libc/cxwhen.c
- sys/libc/libc_proto.h
- unix/boot/bootlib/osproto.h
- unix/hlib/libc/kernel.h
- unix/hlib/libc/kproto.h
- unix/hlib/libc/libc.h
- unix/hlib/libc/spp.h
- unix/os/zcall.c
- unix/os/zfunc.c
- unix/os/zlocpr.c
- unix/os/zmain.c
Having a generic function pointer is the only real use here; so we also rename it.
If the function is going to be used, it is always converted to the required function type.
> Restructure PFI to be used as "generic" function pointer

- sys/libc/callocate.c
- sys/libc/cimdrcur.c
- sys/libc/clexnum.c
- sys/osb/chrpak.c
- sys/osb/chrupk.c
These are in fact `XCHAR`s as they are used as unpacked, not packed strings.
For the moment, this is not important as `PKCHAR` is defined as `XCHAR` (which is a `short int`) https://github.com/iraf-community/iraf/blob/d057e31702155f79ef8387fd6e97514c58600e4f/unix/hlib/libc/spp.h#L96
However, it may be useful to get that in sync with votable, https://github.com/iraf-community/iraf/blob/d057e31702155f79ef8387fd6e97514c58600e4f/vendor/libvotable/votParse_spp.c#L23-L26
> Change a few appearances of PKCHAR

- unix/boot/mkpkg/main.c
This makes it easier to find out where the error happened.
This is a small addition to #267.
> Add the full directory path on mkpkg error exit

- pkg/cl/builtin.c
- pkg/cl/param.c
- pkg/cl/prcache.c
- pkg/cl/task.c
- pkg/ecl/builtin.c
- pkg/ecl/param.c
- pkg/ecl/prcache.c
- pkg/ecl/task.c
- sys/libc/cpoll.c
- sys/libc/cprcon.c
- sys/libc/cprdet.c
- sys/libc/realloc.c
- unix/hlib/libc/iraf_spp.h
- unix/hlib/libc/iraf_stdio.h
The macro **NULL** [must either be an integer 0, or a 0, casted to `void*`](http://port70.net/~nsz/c/c99/n1256.html#6.3.2.3):
> #### 6.3.2.3 Pointers
> [...]
> 3 An integer constant expression with the value 0, or such an expression cast to type void *, is called a null pointer constant. If a null pointer constant is converted to a pointer type, the resulting pointer, called a null pointer, is guaranteed to compare unequal to a pointer to any object or function.
While IRAF locally defines the first (if not already defined), common usage (in gcc and clang) is to have it a pointer. This is unreliable, since if it was defined before, the system definition is kept.
This PR uses the common definition (as a pointer) and then fixes the places where **NULL** was abused as a verbose 0.
> Ensure NULL is a pointer in SPP

- Makefile
This makes the last output lines of a build a bit clearer so that users directly see when the compilation succeeded.
```
============== IRAF build was successful! ===============
Start: Thu Apr 20 15:20:36 UTC 2023
End:   Thu Apr 20 15:31:03 UTC 2023
You may now run "make test" for a quick test of the build
```
> Put a success message after sysgen

- .github/workflows/citest.yml
- Makefile
The `-m32` flag can be better (and more flexibly) added to `CFLAGS` and `LDFLAGS`.
> Remove `CARCH` environment variable

- pkg/cl/mkpkg
- pkg/ecl/mkpkg
The definitions here contradict with the local definitions in IRAF's libc.  For example, **atof()** is `double atof(const char*)` in **stdio.h**, but `double atof(char *)` in **iraf_libc.h**.
In any case we should make sure that we use the correct declarations. That was already set for 32-bit Linux, but it is useful for all platforms.
> Unconditionally remove <stdlib.h> include in (e)cl ytab.c

- .github/workflows/CFF-test.yml
- CITATION.cff
See https://citation-file-format.github.io/
There is a discussion on https://github.com/citation-file-format/citation-file-format/issues/436 about his.
Closes: https://github.com/citation-file-format/citation-file-format/issues/436
> Add CITATION.cff

- unix/hlib/irafarch.sh
Problem taken from [#312](https://github.com/orgs/iraf-community/discussions/312#discussioncomment-6419325):
User or group names may contain a space which confuses the awk script. We replace them by numbers so that it will work independently of the names.
While this is not perfect, it may work for another 20 years.
> Force numeric user/group ids in irafarch.sh symlink retrieval

- unix/hlib/mkiraf.sh
This is a fix of the **mkiraf** script from #268 to correctly set the `iraf` environment variable from `~/.iraf/irafroot` in a local installation. 
Problem was observed in [#312](https://github.com/orgs/iraf-community/discussions/312#discussioncomment-6420664).
> Fix detection of IRAF root on locally installed systems

- CITATION.cff
- INSTALL.md
- README.md
- RELEASE.md
- doc/releases/v217revs.rst
- pkg/cl/cl.par
- pkg/ecl/cl.par
- unix/hlib/login.cl
- unix/hlib/mkiraf.sh
- unix/hlib/zzsetenv.def
Because version 2.17 does not compile anymore on new XCode (macOS), it is useful to soon release a new version.
This PR creates release notes and updates the version number accordingly.
> Prepare new version 2.17.1

- INSTALL.md
- Makefile
- unix/boot/spp/rpp/Makefile
- vendor/libvotable/Makefile
These are a number of small fixes for 2.17.1, found by creating the Debian package:
* typos in rpp/Makefile
* bindir/includedir creation in libvotabe install when they were not created before by cfitsio install
* a missing `DESTDIR` in "make install"
* a missing installation of the sgidispatch manpage
Also, **bison** is required to build IRAF; this should be mentioned in the installation docs.
> Makefile install fixes found when creating the Debian package

- unix/f2c/libf2c/uninit.c
- unix/f2c/patches/0008-C-tweaks-to-make-f2c-compileable-on-Debian-mipsel.patch
This patch was taken from the Debian version of libf2fc. It basically restricts the MIPS changes to IRIX, while Debian/MIPS still runs with (almost) the original settings.
> C tweaks to make f2c compileable on Debian/mipsel

- unix/hlib/setup.sh
This problem was found when using PyRAF with an "inplace" installed IRAF version, as described in https://github.com/iraf-community/pyraf/issues/149. 
Thanks to @monodera for the fix. I kept you as the author of the patch; please let me know if you don't want this.
> Fix iraf$ variable for "inplace" (personal) installation

- Makefile
- unix/hlib/irafcl.man
- unix/hlib/irafcl.sh
This is the name that is used in Debian and other Linux distributions. Rationale is that the names cl and ecl are conflicting with command names of other tools that may be installed on these systems (Common Lisp interpreters). For compatibility, symbolic links to cl and ecl are still provided.
> Rename ecl canonical name to irafcl

- CITATION.cff
This reduces the maintenance requirements of the file.
The "Concept DOI" always points to the latest version.
> Remove version information from CITATION.cff

- noao/lib/Revisions
- noao/lib/obsdb.dat
Three observatories were added in the meantime.
Commits taken from
bb3b2cca5 - added Observatory of Baronnies Provencales
d264bb13b - added Mount Abu Infrared Observatory
d824b9d2 - added LBT to database
> NOIRLAB: Update observatory database 

- unix/boot/rmbin/rmbin.c
- unix/boot/rmfiles/rmfiles.c
This commit from NOIRLABs IRAF may be useful when parts of the target are in a git repository
Original commit:
595416f30 - force exclusion of .git directory from processing
> NOIRLAB: Force exclusion of .git directory from processing in rmbin and rmfiles

- pkg/system/help/helpdb.x
This PR from NOIRLAB IRAF contains two small fixes for the **help** package.
295cd863e - used P2C macro rather than Memi
cdb42fe7d - helpdb fix, use of Memc instead of Memi for mii_readc()
c4d59fa19 - string buffer fix in mii_readc
d56f07bd3 - removed unused decl and pargstr fix
> NOIRLAB: string buffer fix in mii_readc in "help" package

- unix/boot/spp/xc.c
- unix/boot/spp/xpp/decl.c
- unix/boot/spp/xpp/xppcode.c
This adds the NOIRLAB IRAF fixes for possible string overflows.
9101cf98b - prevent string buffer overflow
507b56c42 - fix string overflow possibilities
d56c99de6 - fix string overflow possibilities
> NOIRLAB: Potential xc/xpp string overflow fixes

- noao/mkpkg
- pkg/images/tv/display/t_dcontrol.x
- pkg/images/tv/mkpkg
- pkg/mkpkg
- pkg/proto/color/mkpkg
- pkg/proto/vol/mkpkg
- pkg/tbtables/tbbnll.x
- pkg/tbtables/tbfnew.x
- pkg/tbtables/tbfopn.x
- pkg/tbtables/tbfpri.x
- pkg/utilities/nttools/nttools.par
- pkg/xtools/fixpix/ytpmmap.x
These are small fixes from NOIRLAB IRAF in the **xtools.fixpix** and **tv.display** tasks, and in some **mkpkg** files.
87c9fd7bd - removed old VMS purge definitions
07c698c38 - pointer fix for unused task
0eebf1888 - fix arg type to intrinsic nint()
51673b5e6 - moved -liminterp to the end to compile x_tv.e
d76ccb8ed - removed duplicate iminterp lib from libs
> NOIRLAB: Small fixes in IRAF system packages

- noao/artdata/mktemplates.x
- noao/onedspec/t_specplot.x
- pkg/images/imcoords/src/t_ccmap.x
- pkg/images/imutil/src/imdelete.x
- pkg/images/tv/display/zdisplay.h
- pkg/system/t_fcache.x
- pkg/xtools/mef/mefappfile.x
- sys/etc/miiread.gx
- sys/etc/nmiread.gx
- sys/etc/nmireadb.x
- sys/etc/nmireadc.x
- sys/fio/fmkcopy.x
- sys/fio/frmdir.x
- sys/imio/db/imrenf.x
- sys/imio/dbc/imgcom.x
- sys/imio/dbc/iminfi.x
- sys/imio/iki/fxf/zfiofxf.x
- sys/imio/imgobf.x
- sys/imio/imrdpx.x
- sys/imio/imt/imt.x
- sys/imio/imt/imx.x
- sys/imio/imt/imxbreakout.x
- sys/imio/imt/imxexpand.x
- sys/imio/imt/imxparse.x
- sys/imio/imupk.gx
- sys/mwcs/wftpv.x
- sys/mwcs/wfzpn.x
These commits from NOIRLAB IRAF remove a number of unused declarations throughout the whole system.
2453f858c - removed unused url variable
5a920ed16 - removed unused access() declaration
dd5e01037 - removed unused note() decl
5c384ef4e - removed unused sp/bp/note() decl
75c6374dd - removed unused bp decl
516d03920 - removed unused off/stridxs() decl
64958671b - removed unused j/n/ch/ic/idbgeg/strind/stridx decl
1eb8cede3 - removed unused fd decl
2384c7d58 - commented out bfloat decl in fxfzop
be730aff2 - commented out unused dtemp/rtemp/rscale/roffset decl
5345adc31 - removed unused sum/flen/envgetb()/fntlenb() decl
f33f8e569 - commented out stridx decl
0c3a167cb - removed unused im/immap() decl
f385463af - removed unused exp/envgetb() decl
f4ccde18e - removed unused …
> NOIRLAB: Remove or comment out unused variables

- lib/nmi.h
- math/nlfit/nlfitdefd.h
- math/nlfit/nlfitdefr.h
- sys/etc/gen/nmireadb.x
- sys/etc/miireadc.x
- sys/etc/urlget.x
- sys/fio/fntgfn.x
- sys/fio/vfnmap.x
- sys/fmtio/evvexpr.gy
- sys/gio/fonts/mkfont.c
- sys/imio/immapz.x
- sys/imio/impmmapo.x
- sys/ki/kopdpr.x
- sys/ki/zzrdks.c
- sys/libc/ccnvdate.c
- sys/libc/ccnvtime.c
These are few small fixes for **libsys** from NOIRLABs IRAF.
a2a381742 - fix for GE/GT token confusion
7caef6d96 - backed out of GT/GE token changes
0d7551924 - fixed duplicate GT token def, arg type for min/max/mode/median func
7f33031c8 - commented out test reset of IM_FAST=NO in immapz
ca10e0bc1 - enable fast i/o
f17758f03 - added def for NMI_BOOL
48aab5deb - fix type clash on 32-bit systems
c3041d4cf - modified 1st arg to vvfn_checksum() to int
ebead5f18 - var decl for stridx() values, removed unused strncmp()
091f1d308 - fixed null ref_im reference crashing fixpix task
e2c12a224 - fix for long URLs
> NOIRLAB: Small bugfixes for libsys

- noao/artdata/lists/stcolon.x
- noao/artdata/mktemplates.x
- noao/astcat/src/attools/atfnames.x
- noao/imred/ccdred/ccdred.cl
- noao/imred/ccdred/ccdtest/ccdtest.par
- noao/imred/dtoi/hdicfit/hdicfit.h
- noao/imred/dtoi/hdicfit/hdicgfit.x
- noao/imred/dtoi/hdicfit/hdicggraph.x
- noao/mtlocal/camera/cam_keywords.x
- noao/mtlocal/camera/cam_longhdr.x
- noao/onedspec/odcombine/src/icgscale.x
- noao/rv/rvcorrel.x
- noao/twodspec/longslit/lscombine/src/icgscale.x
This is a collection of small fixes to the NOAO package from NOIRLABs IRAF.
2b3637ea2 - removed unused fp_equalr() decl
99df9ac82 - removed unused decls, fixed pargi error (partially)
a02c7118d - made ADDED_PT a double
346a6ea97 - type conversion fix for hd_redraw()
5e4e40cc0 - added ccdtest.par so pyraf pkg loading works
e11ed0942 - pointer to str conversion for error()
ca9e513fe - fixed type conversion error
35d3a58b6 - fixed type conversion error
8944dc58e - fixed pars() error
1bd2984f2 - fixed pargstr error
> NOIRLAB: Small "noao" package fixes

- unix/boot/generic/generic.c
This PR collects the fixes from NOIRLAB IRAF for the **generic** tool. For reference, these were the original commits:
521776cf8 - initialize forlevel _not really needed (global C variables are always zeroed), but "explicit is better than implicit"_
~~c2275a714 - added test file~~ *not applied; the test file is just a copy of `sys/vops/aabs.gx`.*
~~8e7e31867 - bug fixes and cleanup~~ *not applied; already fixed in a different way (removing `chario.c`)*
~~3adbf0a52 - fixed unused arg~~ *not applied; this is a no-op*
> NOIRLAB: cosmetic change for the "generic" tool

- unix/boot/bootlib/envinit.c
- unix/boot/bootlib/osstrupk.c
- unix/boot/bootlib/ossysfile.c
- unix/gdev/sgidev/sgi2uimp.c
This PR contains a number of (IMO minor) improvements for the bootlib.
6d773e471 - type cast fix for compiler warnings
387c00ae7 - fix sign compareison warnings
e5d528675 - incr size of osfn for irafarch name
~~912574599 - make zzsetenv.def in some locations optional~~ This is fixed differently (via #270)
355199a42 - clarified return of os_access()
> NOIRLAB: minor libboot.a improvements

- sys/osb/i32to64.c
- sys/osb/i64to32.c
This is an attempt to get rid of the IRAF64 provided sources. 
Original commit:
5fe155e3c - license:  rewrote code
The files `unix/as.macintel/zsvjmp.s` and `unix/as.linux64/zsvjmp.s` still contain code from IRAF64, see [noirlab-iraf/iraf-v218#3](https://gitlab.com/nsf-noirlab/csdc/usngo/iraf/iraf-v218/-/issues/3)
> NOIRLAB: Rewrite file taken from IRAF64

- unix/os/alloc.c
- unix/os/getproc.c
- unix/os/zawset.c
- unix/os/zfinfo.c
- unix/os/zfioks.c
- unix/os/zfiond.c
- unix/os/zmain.c
There is a number of patches that fix several glitches in `libos.a`:
a6459af81 - increased 'fname' buffer size to avoid overflow
~~48b2f614f - fixed fcancel() macro for OSX~~
997ff1c63 - deprecated use of rcmd() on OSX systems
28a9b9e7c - ensure null termination following strncpy(), gcc 8 -Wstringop-truncation err
1dfb2a7af - ensure null termination following strncpy(), gcc 8 -Wstringop-truncation err
~~ab2ec08d9 - ensure null termination following strncpy(), gcc 8 -Wstringop-truncation err~~
a55a788a0 - fix sign compare
0e72cfc3e - fix clobber warning from linux64
d8226de5e - fix compiler warnings from linux64
The commit ab2ec08d9 looks a bit weird:
```diff
diff --git a/unix/os/zfiond.c b/unix/os/zfiond.c
index 294a6eb2b..33d779b9c 100644
--- a/unix/os/zfiond.c
+++ b/unix/os/zfiond.c
@@ …
```
> NOIRLAB: several patches for libos.a

- unix/os/zxwhen.c
This is an alternative to NOIRLAB IRAFs 48b2f614fbaf28219bcc35e291b440fcc11be03f, which defines **fcancel()** as [**setvbuf()**](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/setvbuf.3.html) on macOS: https://github.com/iraf-community/iraf/blob/3761a03d6bb3d91e5da0a9562e778654f59ab2a3/unix/os/zxwhen.c#L90-L96
**setvbuf()** is not what **fcancel()** is supposed to do, namely to cancel any buffered output. Instead, it just makes the output unbuffered. i.e. when applying this patch, stdout will become unbuffered for the rest of the session after ^C. Also, **setvbuf()** is not macOS specific but part of the standard C library (and therefore also available for Linux). And, hard-coding `_IONBF` instead of using the proper include file …
> Use fpurge/__fpurge to cancel buffered output

- Makefile
- test/run_tests
- unix/boot/spp/xc.c
- unix/boot/spp/xc.hlp
- unix/boot/spp/xc.man
- unix/hlib/mkpkg.inc
Major driver here is the removal of the arch dependent `-m32` flag (for i386). This flag shadowed a missing linker flag in the Makefile; this should help us moving towards cross compileability.
Then, all "shared image" support was removed. This was modelled for the SunOS shared library model, which involved patching a shared image. On Linux and macOS, shared library support works completely different, so it is removed here. I we ever want to enable a libiraf.so shared library, we will anyway re-implement this (maybe based on the Digital Unix version which is closer to what is used today).
Finally, a few variables and options were removed that are no longer in use. For compatibility, they stay as no-op in the argument list.
> Remove outdated options from XC

- unix/hlib/mkfloat.csh
- unix/hlib/mkfloat.sh
Traditionally, the "mkfloat" script was a C shell, which was indicated by its suffix. This was converted to a POSIX shell script long time ago, without suffix.
The script however may be run during the build of external packages, and they may refer to `mkfloat.csh`. To allow an easier migration, we provide a compatiblity link here.
Although there is no known package that uses `mkfloat.sh`, we also provide it here.
> Provide compatibility link to mkfloat.csh

- unix/hlib/extpkg.cl
Taken from NOIRLABs IRAF, 0d94516a2c54ce973061a55b147f87da1e0df6e2, author @mjfitzpatrick
> Don't add to helpdb var if no helpdb.mip (sqiid/upsqiid)

- unix/os/irafpath.c
We first try in bin.$IRAFARCH (if defined) and then also in bin, to allow mixing multiarch and singlearch installations.
> Allow empty IRAFARCH in irafpath()

- sys/libc/system.c
- unix/os/zfiobf.c
- unix/os/zfioks.c
The first argument in ZOPNND() should really be declared as a `char *`. However it is a SPP called function and therefore limited to the SPP data types; so the first argument is declared as `PKG_CHAR *` (which is a `short int`). Therefore we need to cast it when called from C.
Another point is the wrong pointer type in zfioks.c, which is resolved here as well.
Fixes: #395
> Fix build on Fedora-40: Use explicit pointer casts in some more places

- pkg/tbtables/tbttyp.x
Taken over from NOIRLab code:
* fa05e8e09b0ef742858a28cc885d690c062600a3 removed file caching code
* d55036b96e79363375b1c44da67c4673a4e84bc6 automatically add .tab extn if necessary
The first one removes a code fragment that was permanently disabled.
> NOIRLAB: tbtables: automatically add .tab extn if necessary

- INSTALL.md
On the Debian 64-bit HURD architecture is [built and tested sucessfully](https://buildd.debian.org/status/logs.php?pkg=iraf&arch=hurd-amd64). That's why we can add this architecture to the list of supported architectures.
> Add hurd64 to the list of supported architectures

- .github/workflows/citest.yml
Ubuntu 24.04 for linux64 (unchanged)
Ubuntu 22.04 for linux (32 bit)
MacOS 13 for macintel
MacOS 15 for macos64 (ARM)
For Macintel, the optimization is set to -O1 because with -O2 the compilation is buggy and the `rmfiles.e unix/hlib/strip.iraf` call fails with
illegal `-f progfile' switch
This seems a compiler bug, as there is nothing in `rmfiles.c` that could cause this, https://github.com/iraf-community/iraf/blob/c679e01fe5a2d8ecec7f7477eefde20cf4f249e0/unix/boot/rmfiles/rmfiles.c#L81-L88
> Use newer images for builds

- pkg/cl/decl.c
- pkg/cl/opcodes.c
- unix/hlib/f77.sh
This is the companion to https://github.com/iraf-community/x11iraf/pull/75. gcc-15 defaults to C23 as C standard, which interprets empty argument lists in functions as void, i.e. **foo()** is now equivalent to **foo(void)**.
This is a problem with f2c generated code, because this comes without proper prototypes (they don't exist in Fortran and in SPP). So, the only solution here is to fix the C standard to one where empty function args are interpreted as an unspecified argument list.
The C files here are already mostly C23 compliant, except for two places in pkg/cl, which are now fixed as well.
Additionally to the CI tests here this was tested with gcc-15 and clang-19.
See also [Debian#1096852](https://bugs.debian.org/1096852)
> Make IRAF compileable with gcc-15 and newer clang

- unix/boot/mkpkg/scanlib.c
- unix/boot/mkpkg/tok.c
Specifically, don't print warnings if the first file does not exist in `$ifolder`, or of the second file does not exist in `$ifnewer`.
Reason is that `$ifolder`/`$ifnewer` are used to (re-)create a file when it is older than its origin. Usually however the generated file does not exist at all in the beginning; this is a normal case and shall not cause a warning.
> Don't print some warnings in mkpkg's `$ifolder`/`$ifnewer`

- sys/mkpkg
- unix/boot/mkpkg/host.c
- unix/boot/rmfiles/rmfiles.c
- unix/boot/spp/rpp/rppfor/errchk.f
- unix/boot/spp/rpp/rpprat/errchk.r
- unix/boot/spp/xc.c
- unix/boot/wtar/wtar.c
- unix/boot/xyacc/y1.c
- unix/hlib/f77.sh
- unix/os/zalloc.c
This removes many of the warnings; also one bug in **rmfiles** was fixed here.
Most of the warnings came from the compilation of **rpp**. The majority was because f2c converts f77 **SUBROUTINE** into C **int()** functions (on purpose), but does not apply a return value then. These warnings are removed by adding `-Wno-return-type` to the compiler flags.
The other fixes were about unused code, where this code just got removed.
There are some warnings left:
1. many "unused but set variable" warning, because **rpp** often ignores the return value of functions (but sometimes uses it). I don't want to silence this, because unused variables are generally a good cause for a warning.
2. In function ‘penencode’, inlined from ‘translate’ at sgi2ueps.c:328:10 (this is most probably a bug):
``` …
```
> Silence warnings

- doc/releases/v218revs.rst
- pkg/cl/main.c
- pkg/ecl/main.c
This fixes the build on 32 bit. It was on Debian already for a while, but was forgotten to push to upstream.
> Fix type of jumpcon in (e)cl/main.c
